### PR TITLE
closes #46 and closes #74

### LINKED ISSUE #46: Implement Create Project API
[ ] Define endpoint
[ ] Implement API

### LINKED ISSUE #74: Add user authentication to POST project
requires login #6

### PR DESCRIPTION
**Pull request by sfiquet**
POST a project

User authentication will need to be added later.

### CODE REVIEW

**Comment by Heyjp** [comment]
So it looks good but I have a couple of questions just in general. 

1) What is res.location for? Does that redirect the user to the then published project? or does it just send information to the client and then then are they redirected from there?

2) All your requests are written with the information being sent as JSON, should I be updating the register and login route to do the same? Is there a benefit to using json over just sending a regular object from a form?

3) When the registration and login is working, are you still going to be sending the user information from the client or will that be handled from taking the info from `req.user` or will they be referenced against each other?

Otherwise I'm happy to merge what's here. and struggled to find any issues.

**Comment by sfiquet** [comment]
1. `res.location` represents the `Location` HTTP header. It's just for telling the client where the new resource can be accessed. It's up to the client to decide if they want to use it and how. It's part of the standard for returning 201 after a POST (https://tools.ietf.org/html/rfc2616#section-9.5). 

Now that I've had time to think about it, it was a bad idea to return a 201 because I didn't add code to serve that URI. It will be needed when we let the user edit the project but for now it doesn't exist. Maybe I should just return a 200. In addition I didn't originally mean to return the whole object in the body but I added it because it made writing the last tests easier. That fits well with the 200 too.

This is what the [standard](https://tools.ietf.org/html/rfc2616#section-10.2.1) says:
- 201 returns the URI of the newly created resource in the Location header, plus additional info in the body
> The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. The origin server MUST create the resource before returning the 201 status code.
- 200 returns "an entity describing or containing the result of the action" for POST

I'll change it to a 200.

**Comment by sfiquet** [comment]
2. The short answer is I don't know. The point of using JSON was to decouple the server from the client. If you use the form format it means the server knows about the client's form so they're tightly coupled. If you change the client, you might have to change the server as well.

I've been trying to go for a RESTful API where the server just handles the data and doesn't know anything about the user interface. But the more I learn about REST, the more I see how much more there is to learn. It's probably too much work to do it properly given our deadline. Right now my opinion is that if it works don't fix it.

**Comment by sfiquet** [comment]
3. I don't think it can stay the way it is. I went for something that I could use for testing but I've been thinking about this and it can't stay that way.

If we use sessions, I think I can just get the user information from `req.user`, provided it has the username and id. I think behind the scenes Passport does all the authentication through cookies in the request header but it's hidden from us and we don't have to worry about it. Either that or I didn't understand how it works.

There is something in Passport's documentation that mentions that APIs don't need sessions and require the user credentials to be sent every time. If we go that route, the client would need to send the username and password every time and the server would give those to passport for authentication, just like login does. Maybe it's not necessary here. If we wanted to completely decouple the server from the client, e.g. to allow third parties to use our API, we would do it that way but we don't have time and it's not necessary, so no.

So I think when we merge with registration and login, I'll change it to remove the user info completely.

**Comment by sfiquet** [comment]
I adapted the code for authentication. 

Then I got into trouble with Jest: When running `projectsPOST.int.test.js` on its own, everything passed. When running it as part of command `npm run testint` the authentication failed, causing most tests to fail. Sometimes `auth.int.test.js` also failed. Jest runs tests in parallel by default and I believe that causes the integration tests to interfere with each other. I changed the script to run tests sequentially and that magically fixed it. I don't think Jest is meant to do integration testing.

**Comment by Heyjp** [comment]
Looks good, thank you for fixing the `Auth` files as well.  I see you've broken up the files into `get` & `post` is this something we should look to do with all the api requests. 

Also in `projectsPost.int.test.js`, `setupUser` is written as an async function but it doesn't make use of await. But I'm also unsure about what dictates when you should and shouldn't use it. So I will be merging with development.

**Comment by sfiquet** [comment]
I don't know whether we should separate the tests for the API requests, maybe. The reason I did it is because most of the tests for POST were failing and running the whole file was slow. Separating them allowed me to just run the POST tests by running Jest on the command line.

For `setupUser` the `async` keyword comes from my early attempt to write the function using `async/await` and failing miserably. Saving the user and logging in happened in any order. I rewrote it with callbacks and forgot to remove `async`. 

But I just checked MDN, it's fine to have it there:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function:
> An async function can contain an await expression [...]

> The async function declaration defines an asynchronous function, which returns an AsyncFunction object.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction
> In JavaScript every asynchronous function is actually an AsyncFunction object.

**Pull request merged**
